name: store_manager
description: A hash map based store manager for dart and flutter.
version: 1.1.0
homepage: https://github.com/Ayush-Suman/store-manager

environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
